[2023-11-05T12:11:11.428+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: experiment.get_data manual__2023-11-05T08:11:09.131264+00:00 [queued]>
[2023-11-05T12:11:11.430+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: experiment.get_data manual__2023-11-05T08:11:09.131264+00:00 [queued]>
[2023-11-05T12:11:11.430+0400] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-05T12:11:11.437+0400] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-05 08:11:09.131264+00:00
[2023-11-05T12:11:11.439+0400] {standard_task_runner.py:57} INFO - Started process 48934 to run task
[2023-11-05T12:11:11.442+0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'experiment', 'get_data', 'manual__2023-11-05T08:11:09.131264+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/experiment.py', '--cfg-path', '/tmp/tmpf6ygvtub']
[2023-11-05T12:11:11.443+0400] {standard_task_runner.py:85} INFO - Job 5: Subtask get_data
[2023-11-05T12:11:11.464+0400] {task_command.py:416} INFO - Running <TaskInstance: experiment.get_data manual__2023-11-05T08:11:09.131264+00:00 [running]> on host primary
[2023-11-05T12:11:11.490+0400] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='experiment' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T08:11:09.131264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T08:11:09.131264+00:00'
[2023-11-05T12:11:11.491+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T12:11:11.492+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/pyretttt/repos/mlops4/scripts/get_data.py']
[2023-11-05T12:11:11.495+0400] {subprocess.py:86} INFO - Output:
[2023-11-05T12:11:11.515+0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T12:11:11.515+0400] {subprocess.py:93} INFO -   File "/home/pyretttt/repos/mlops4/scripts/get_data.py", line 6, in <module>
[2023-11-05T12:11:11.515+0400] {subprocess.py:93} INFO -     logger = logging.getLoger('get_data')
[2023-11-05T12:11:11.515+0400] {subprocess.py:93} INFO - AttributeError: module 'logging' has no attribute 'getLoger'. Did you mean: 'getLogger'?
[2023-11-05T12:11:11.518+0400] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T12:11:11.521+0400] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T12:11:11.523+0400] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=experiment, task_id=get_data, execution_date=20231105T081109, start_date=20231105T081111, end_date=20231105T081111
[2023-11-05T12:11:11.529+0400] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 48934)
[2023-11-05T12:11:11.533+0400] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T12:11:11.540+0400] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
